---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reverter-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - chronos.ocp.run
  resources:
  - changeevents
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - chronos.ocp.run
  resources:
  - changeevents/status
  verbs:
  - patch
  - update
- apiGroups:
  - chronos.ocp.run
  resources:
  - resourcesnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - chronos.ocp.run
  resources:
  - revertoperations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chronos.ocp.run
  resources:
  - revertoperations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  verbs:
  - bind
  - create
  - escalate
  - get
  - patch
  - update
