//go:build !ignore_autogenerated

/*
Copyright 2026 Chronos project and its authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Actor) DeepCopyInto(out *Actor) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImpersonatedGroups != nil {
		in, out := &in.ImpersonatedGroups, &out.ImpersonatedGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Actor.
func (in *Actor) DeepCopy() *Actor {
	if in == nil {
		return nil
	}
	out := new(Actor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeEvent) DeepCopyInto(out *ChangeEvent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeEvent.
func (in *ChangeEvent) DeepCopy() *ChangeEvent {
	if in == nil {
		return nil
	}
	out := new(ChangeEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChangeEvent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeEventList) DeepCopyInto(out *ChangeEventList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChangeEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeEventList.
func (in *ChangeEventList) DeepCopy() *ChangeEventList {
	if in == nil {
		return nil
	}
	out := new(ChangeEventList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChangeEventList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeEventSpec) DeepCopyInto(out *ChangeEventSpec) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	out.Target = in.Target
	in.Actor.DeepCopyInto(&out.Actor)
	if in.ChangedFields != nil {
		in, out := &in.ChangedFields, &out.ChangedFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeEventSpec.
func (in *ChangeEventSpec) DeepCopy() *ChangeEventSpec {
	if in == nil {
		return nil
	}
	out := new(ChangeEventSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChangeEventStatus) DeepCopyInto(out *ChangeEventStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChangeEventStatus.
func (in *ChangeEventStatus) DeepCopy() *ChangeEventStatus {
	if in == nil {
		return nil
	}
	out := new(ChangeEventStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChronosConfig) DeepCopyInto(out *ChronosConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChronosConfig.
func (in *ChronosConfig) DeepCopy() *ChronosConfig {
	if in == nil {
		return nil
	}
	out := new(ChronosConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChronosConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChronosConfigList) DeepCopyInto(out *ChronosConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChronosConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChronosConfigList.
func (in *ChronosConfigList) DeepCopy() *ChronosConfigList {
	if in == nil {
		return nil
	}
	out := new(ChronosConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChronosConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChronosConfigSpec) DeepCopyInto(out *ChronosConfigSpec) {
	*out = *in
	in.Defaults.DeepCopyInto(&out.Defaults)
	if in.NamespaceOverrides != nil {
		in, out := &in.NamespaceOverrides, &out.NamespaceOverrides
		*out = make([]NamespacePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChronosConfigSpec.
func (in *ChronosConfigSpec) DeepCopy() *ChronosConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ChronosConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChronosConfigStatus) DeepCopyInto(out *ChronosConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChronosConfigStatus.
func (in *ChronosConfigStatus) DeepCopy() *ChronosConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ChronosConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterPolicy) DeepCopyInto(out *FilterPolicy) {
	*out = *in
	if in.ExcludeControllerActors != nil {
		in, out := &in.ExcludeControllerActors, &out.ExcludeControllerActors
		*out = new(bool)
		**out = **in
	}
	if in.ExcludeNoiseSecrets != nil {
		in, out := &in.ExcludeNoiseSecrets, &out.ExcludeNoiseSecrets
		*out = new(bool)
		**out = **in
	}
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeSecretTypes != nil {
		in, out := &in.ExcludeSecretTypes, &out.ExcludeSecretTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeFields != nil {
		in, out := &in.ExcludeFields, &out.ExcludeFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeFields != nil {
		in, out := &in.IncludeFields, &out.IncludeFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RedactKeys != nil {
		in, out := &in.RedactKeys, &out.RedactKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RedactFields != nil {
		in, out := &in.RedactFields, &out.RedactFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterPolicy.
func (in *FilterPolicy) DeepCopy() *FilterPolicy {
	if in == nil {
		return nil
	}
	out := new(FilterPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacePolicy) DeepCopyInto(out *NamespacePolicy) {
	*out = *in
	in.FilterPolicy.DeepCopyInto(&out.FilterPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacePolicy.
func (in *NamespacePolicy) DeepCopy() *NamespacePolicy {
	if in == nil {
		return nil
	}
	out := new(NamespacePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedactionEntry) DeepCopyInto(out *RedactionEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedactionEntry.
func (in *RedactionEntry) DeepCopy() *RedactionEntry {
	if in == nil {
		return nil
	}
	out := new(RedactionEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Requester) DeepCopyInto(out *Requester) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Extra != nil {
		in, out := &in.Extra, &out.Extra
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Requester.
func (in *Requester) DeepCopy() *Requester {
	if in == nil {
		return nil
	}
	out := new(Requester)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSnapshot) DeepCopyInto(out *ResourceSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSnapshot.
func (in *ResourceSnapshot) DeepCopy() *ResourceSnapshot {
	if in == nil {
		return nil
	}
	out := new(ResourceSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSnapshotList) DeepCopyInto(out *ResourceSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResourceSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSnapshotList.
func (in *ResourceSnapshotList) DeepCopy() *ResourceSnapshotList {
	if in == nil {
		return nil
	}
	out := new(ResourceSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSnapshotSpec) DeepCopyInto(out *ResourceSnapshotSpec) {
	*out = *in
	out.Target = in.Target
	in.CapturedAt.DeepCopyInto(&out.CapturedAt)
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ContentRef != nil {
		in, out := &in.ContentRef, &out.ContentRef
		*out = new(StorageReference)
		**out = **in
	}
	if in.Redactions != nil {
		in, out := &in.Redactions, &out.Redactions
		*out = make([]RedactionEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSnapshotSpec.
func (in *ResourceSnapshotSpec) DeepCopy() *ResourceSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSnapshotStatus) DeepCopyInto(out *ResourceSnapshotStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSnapshotStatus.
func (in *ResourceSnapshotStatus) DeepCopy() *ResourceSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevertOperation) DeepCopyInto(out *RevertOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevertOperation.
func (in *RevertOperation) DeepCopy() *RevertOperation {
	if in == nil {
		return nil
	}
	out := new(RevertOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RevertOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevertOperationList) DeepCopyInto(out *RevertOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RevertOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevertOperationList.
func (in *RevertOperationList) DeepCopy() *RevertOperationList {
	if in == nil {
		return nil
	}
	out := new(RevertOperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RevertOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevertOperationSpec) DeepCopyInto(out *RevertOperationSpec) {
	*out = *in
	out.Target = in.Target
	if in.RequestedBy != nil {
		in, out := &in.RequestedBy, &out.RequestedBy
		*out = new(Requester)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevertOperationSpec.
func (in *RevertOperationSpec) DeepCopy() *RevertOperationSpec {
	if in == nil {
		return nil
	}
	out := new(RevertOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevertOperationStatus) DeepCopyInto(out *RevertOperationStatus) {
	*out = *in
	if in.ManualStepsRequired != nil {
		in, out := &in.ManualStepsRequired, &out.ManualStepsRequired
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevertOperationStatus.
func (in *RevertOperationStatus) DeepCopy() *RevertOperationStatus {
	if in == nil {
		return nil
	}
	out := new(RevertOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageReference) DeepCopyInto(out *StorageReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageReference.
func (in *StorageReference) DeepCopy() *StorageReference {
	if in == nil {
		return nil
	}
	out := new(StorageReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetObjectReference) DeepCopyInto(out *TargetObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetObjectReference.
func (in *TargetObjectReference) DeepCopy() *TargetObjectReference {
	if in == nil {
		return nil
	}
	out := new(TargetObjectReference)
	in.DeepCopyInto(out)
	return out
}
