apiVersion: v1
kind: ConfigMap
metadata:
  name: chronos-console-plugin
  namespace: chronos-system
  labels:
    app: chronos-console-plugin
    app.kubernetes.io/part-of: chronos
data:
  nginx.conf: |
    error_log /dev/stdout info;
    events {}
    http {
      access_log         /dev/stdout;
      include            /etc/nginx/mime.types;
      default_type       application/octet-stream;
      keepalive_timeout  65;
      server {
        listen              9443 ssl;
        listen              [::]:9443 ssl;
        ssl_certificate     /var/cert/tls.crt;
        ssl_certificate_key /var/cert/tls.key;
        root                /usr/share/nginx/html;
      }
    }
