apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: chronos
    app.kubernetes.io/managed-by: kustomize
    chronos.ocp.run/role: correlator
  name: correlator
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: chronos
    app.kubernetes.io/managed-by: kustomize
  name: correlator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: correlator-role
subjects:
- kind: ServiceAccount
  name: correlator
  namespace: system
