---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: correlator-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - get
- apiGroups:
  - chronos.ocp.run
  resources:
  - changeevents
  verbs:
  - get
  - list
  - patch
  - update
  - watch
